modLoader="javafml"
license="MIT"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/zehmaria/resourcefullveins/issues"
displayURL="https://github.com/zehmaria/resourcefullveins"
logoFile="logo.png"

[[mods]]
    modId="resourcefullveins"
    version="${file.jarVersion}"
    displayName="Resourcefull Veins"
	authors="zeh_maria"
    description="Find your resource-fix already sitting around in your world!"

[[dependencies.resourcefullveins]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.resourcefullveins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
