modLoader="javafml"
license="MIT"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/zehmaria/peaks/issues"
displayURL="https://github.com/zehmaria/peaks"
logoFile="logo.png"

[[mods]]
    modId="peaks"
    version="${file.jarVersion}"
    displayName="Peaks"
	authors="zeh_maria"
    description="Find your resource-fix already sitting around in your world!"

[[dependencies.peaks]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.peaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
