modLoader="javafml"
license="MIT"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/zehmaria/resourcefullveins/issues"
displayURL="https://github.com/zehmaria/resourcefullveins"
logoFile="logo.png"

[[mods]]
    modId="peaks"
    version="${file.jarVersion}"
    displayName="Peaks"
	authors="zeh_maria"
    description="Find your resource-fix already sitting around in your world!"

[[dependencies.peaks]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.peaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
