modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/zehmaria/peaks/issues"
license="MIT"

[[mods]]
    modId="peaks"
    version="${version}"
    displayName="Peaks"
    displayURL="https://github.com/zehmaria/peaks"
	authors="zeh_maria"
    logoFile="logo.png"
    description="Find your resource-fix already sitting around in your world!"

[[dependencies.peaks]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version}"
    side="BOTH"

[[dependencies.peaks]]
    modId="minecraft"
    type="required"
    versionRange="${mc_version}"
    side="BOTH"
